---
- name: Install Choco packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    ignore_checksums: "{{ item.ignore_checksums | default(false) }}"
    params: "{{ item.params | default(omit) }}"
    choco_args: "{{ item.choco_args | default(omit) }}"
  loop: "{{ choco_packages }}"
