---
- name: Install PowerToys.
  chocolatey.chocolatey.win_chocolatey:
    name: powertoys
    state: present

- name: Setup my PowerToys configuration.
  ansible.windows.win_copy:
    src: "{{ playbook_dir }}/dotfiles/PowerToys/"
    dest: '%USERPROFILE%\\AppData\\Local\\Microsoft\\PowerToys\\'
