---
- name: Install Window Terminal.
  chocolatey.chocolatey.win_chocolatey:
    name: microsoft-windows-terminal
    state: present

- name: Setup my Terminal configuration.
  ansible.windows.win_copy:
    src: "{{ playbook_dir }}/dotfiles/WinTerminal/"
    dest: '%USERPROFILE%\\AppData\\Local\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\'
