---
do_init: true
# TODO: remove init task

configure_explorer: true

configure_hostname: false
custom_hostname: windows-ansible

configure_start_menu: true
configure_taskbar: true

disable_mouse_acceleration: true

remote_desktop_enabled: false
remove_desktop_icons: false

set_sound_scheme: false

change_power_plan: false
power_plan: "high performance"

choco_packages:
  # To specify state, version, and args
  # - name: auto-dark-mode
  #   version: "2022.002.20191"
  #   state: latest
  #   choco_args: --ignorechecksum
  # TODO: consider install git in setup script
  - git
  # TODO: consider move oh-my-posh to separate task
  - oh-my-posh
  - gsudo
  - powertoys
  - python3
  - notion
  - sharex
  - vlc
  - name: vscode
    choco_args: --params /NoDesktopIcon
  - visualstudio2022community
  - intellijidea-community
  - notepadplusplus
  # - cmake
  # - svn
  # - tortoisesvn
  - diffmerge
  # TODO: test nvm why not work
  - nvm
  # - postman
  - name: figma
    choco_args: --ignorechecksum
  # - dbeaver
  # - doxygen.install
  # - graphviz
  - powershell-core
  # TODO: test postgresql13 why cannot install
  - name: postgresql13
    choco_args: --params '/Password:admin' --params-global
  - name: thunderbird
    choco_args: --params /NoDesktopShortcut
  - 7zip
  - anydesk
  - filezilla
  - hwmonitor
  - docker-desktop
  - jetbrainsmononf
  - zalopc
  - vagrant
  - virtualbox
  # - steam-client
  # - epicgameslauncher
  # - battle.net
  # - origin
  # - goggalaxy
  # - ubisoft-connect
  # - googledrive
  # - grammarly
  # - autohotkey
  # - packer
  # - geforce-experience
  # TODO: consider make a task to install emacs and set up doom emacs
  # - emacs
  # TODO: consider make a task to setup neovim
  # - neovim
  - name: firefox
    choco_args: --params /NoDesktopShortcut

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  - "*"
  # - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  # - Security Updates
  # - Service Packs
  # - Tools
  # - Update Rollups
  # - Updates
  # - Upgrades

install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# This should be off if done via internal wsl
# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: true
wsl2_distribution:

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

winget_packages:
  - name: AgileBits.1Password
    source: winget
  - name: Spotify.Spotify
    source: winget
  - name: Telegram.TelegramDesktop
    source: winget
  - name: Microsoft.Skype
    source: winget
  # Messenger
  - name: 9WZDNCRF0083
    source: msstore
  # GoTiengViet
  - name: 9P1F8XG2LZM9
    source: msstore

defrag_volumes: false
include_volumes:
  - C
  - D
