---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/updates.yml
      when: install_windows_updates
      tags: ["updates"]

    - import_tasks: tasks/debloat.yml
      when: remove_bloatware
      tags: ["debloat"]

    - import_tasks: tasks/winget_packages.yml
      tags: ["winget"]

    - import_tasks: tasks/choco_packages.yml
      tags: ["choco"]

    # - import_tasks: tasks/local_packages.yml
    #   tags: ["local"]

    - import_tasks: tasks/desktop.yml
      when: remove_desktop_icons
      tags: ["desktop"]

    - import_tasks: tasks/windows_features.yml
      when: install_windows_features
      tags: ["windows_features"]

    - import_tasks: tasks/wsl2.yml
      when: install_wsl2
      tags: ["wsl"]

    - import_tasks: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]

    - import_tasks: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]

    - import_tasks: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu"]

    - import_tasks: tasks/mouse.yml
      when: disable_mouse_acceleration
      tags: ["mouse"]
